### PR TITLE
Fix hide open animation

### PR DESCRIPTION
**Pull request by Stoope**
Closes: #61 
Behavior before:
deepin-screen-recorder_Select area_20190510160327
 
Behavior after:
deepin-screen-recorder_Select area_20190510160117

### CODE REVIEW

**Comment by xmuli** [comment]
Thanks for the code, it helps us merge better!

**Comment by Stoope** [comment]
@xmuli Hi! I can't see any conflict.

**Comment by rafaeldev** [comment]
Hi guys!
Here:
image

**Comment by Stoope** [comment]
@rafaeldev Hi! I see. How can I fix it? What line of code should I resolve?

**Comment by xmuli** [comment]
Because of its existence, I can’t click merge and it’s recommended to merge to
  The default branch "uos"; then you will see the merged effect faster
image

**Comment by rafaeldev** [comment]
@Stoope you need merge master branch into your branch.
I think you need use a editor like Atom to resolve resolve that.

**Pull request closed without merging**
