### PR TITLE
Fix: preview glitches

### PR DESCRIPTION
**Pull request by SiamSami**
It is a fix to the preview glitches. Now we can use the preview feature without any graphical glitch.
It's a fix to these issues,
https://github.com/linuxdeepin/developer-center/issues/1119
https://github.com/linuxdeepin/developer-center/issues/1200
https://github.com/linuxdeepin/developer-center/issues/1337

### CODE REVIEW

**Comment by SiamSami** [comment]
@BLumia Is it going to be merged or not?

**Comment by BLumia** [comment]
> @BLumia Is it going to be merged or not?

Just please, don't rush me, I cannot do anything about merge your pull request before the v20 code release. I really cannot merge pull request before they do sync the internal repo to public.

**Comment by SiamSami** [comment]
@BLumia I mean, is it going to be included in v20's source code or not?

**Comment by SiamSami** [comment]
@BLumia It's okay. Take your time :)

**Comment by SiamSami** [comment]
@BLumia It seems that the v20 code has been released and this fix still seems to work with the v20 version of the dock.

**Comment by BLumia** [comment]
> @BLumia It seems that the v20 code has been released and this fix still seems to work with the v20 version of the dock.

cc @xmuli

**Comment by SiamSami** [comment]
Closing this and starting another pull request on "uos" branch

**Pull request closed without merging**
