### PR TITLE
Fix: a missing dependency in CI

### PR DESCRIPTION
**Pull request by RigoLigoRLC**

### CODE REVIEW

**Comment by RigoLigoRLC** [comment]
@xmuli CI is back up working now. Please merge this PR so CI checks will recover.

**Comment by RigoLigoRLC** [comment]
I tried to squash my commits but this has affected their parent commit, so this is not going to work. This PR is going to be closed and another one with correct commits will be added later.

It appears that Deepin will only accept PRs with one commit only.

**Comment by RigoLigoRLC** [comment]
It seems my CI fix no longer works! It is missing `libicui18n.so` so apparently this might not be properly installed. I will also have to fix this one.

**Comment by xmuli** [comment]
> It appears that Deepin will only accept PRs with one commit only.

Due to gerrit's own limitations, only one pr can be accepted at a time

**Pull request closed without merging**
