### PR TITLE
fix: remove redundant dependency on dde-network-utils

### PR DESCRIPTION
**Pull request by felixonmars**
Remove redundant dependency on dde-network-utils.

Log: Remove redundant dependency on dde-network-utils

### CODE REVIEW

**Comment by wineee** [comment]
/+1

**Comment by wubw1992** [comment]
dde-network-utils is a 104x network related service. Why delete it
In addition, please create an issue and explain the reason for submission

**Review by ut003640 — APPROVED** [review]

**Review by ssk-wh — APPROVED** [review]

**Pull request merged**
