### PR TITLE
Update trashplugin.cpp

### PR DESCRIPTION
**Pull request by ElianVanCutsem**
added if statement for better spelling.
When 0 files are in trash, it should say 0 files, not 0 file.
So instead of `if (count < 2){ "file" } else { "files"} `
it's `if (count == 1){ "file" } else { "files"}`

### CODE REVIEW

**Comment by BLumia** [comment]
btw, since all v20 projects (dde-dock included) is still under heavy development in an internal GitLab instance and v20 is still not yet ready for release, we could only manually cherry-pick your patch into our master codebase. The source release will comes with the v20 release so please keep an eye on it :)

**Comment by ElianVanCutsem** [comment]
@BLumia oh, i'm excited to see which features v20 will bring. This is a patch that should be included since it's so simple :) 
Have fun developing ;) i'll change my commits to be only one commit.

**Comment by ElianVanCutsem** [comment]
> Hi and seems you submited one-line single change into two commits. Please consider squash it into one commit :)

changed it to be only one commit.

**Comment by ElianVanCutsem** [comment]
Yup, That's great! Is there some ki'd of alpha/beta testing? If there is. I'm interested to join.

**Comment by BLumia** [comment]
> Is there some ki'd of alpha/beta testing? If there is. I'm interested to join.

Currently no, but the source release may comes a little bit earlier than beta release. I'll let you know if there are any news about that :D

**Comment by BLumia** [comment]
Hi and here are some update. There will probably a public v20 beta release in the upcoming days, but source release may probably comes when the final version of v20 get released, so keep an eye on that :)

**Comment by BLumia** [comment]
Hi and now we are in the progress of releaseing the v20 codebase to GitHub, and the source of dde-dock is sync to GitHub now. If you are still interested in submit your patch, feel free to do it and we'll try to help you get it merged :)

**Comment by ElianVanCutsem** [comment]
That's great to hear. I'll take a look

**Comment by ElianVanCutsem** [comment]
I fixed this error again in PR #267

**Pull request closed without merging**
