### PR TITLE
fix: Datetime 24 format at plugin initialization

### PR DESCRIPTION
**Pull request by Foxei**
This fix refers to issue https://github.com/linuxdeepin/developer-center/issues/1444. There is already another pull request https://github.com/linuxdeepin/dde-dock/pull/248 that changes much more code. My changes are minimal and fulfill the task as well.

### CODE REVIEW

**Comment by BLumia** [comment]
Hello and I just would like to let you know we are during a transition period between moving our workflow to a self-host GitLab instance, community patchs review will become very slow during this period.

cc @justforlxz

**Comment by SiamSami** [comment]
@BLumia Is it done now?

**Comment by BLumia** [comment]
> @BLumia Is it done now?

No it's not, and since I don't manage this process so I'm also not sure when this process will be done. Sorry about that.

**Comment by xmuli** [comment]
It should have been fixed (but thanks for submitting it)

**Pull request closed without merging**
